import importlib.util
from pathlib import Path

import pytest

REPO_ROOT = Path(__file__).resolve().parents[1]

FIXTURE_WITH_MARKERS = """# CURRENT STATE

Some narrative prose above the table, untouched by --apply.

## Build state

| | Value | Notes |
|---|---|---|
| Agent infrastructure | hand-maintained row | stays put |

<!-- BUILD-STATE:START (generated by `python tools/state.py --apply` -- do not hand-edit between these markers) -->

OLD CONTENT THAT SHOULD BE REPLACED

<!-- BUILD-STATE:END -->

## Statistical constants in force

More prose below, also untouched.
"""


def _load_module():
    spec = importlib.util.spec_from_file_location("state_under_test", str(REPO_ROOT / "tools" / "state.py"))
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


@pytest.fixture
def st(tmp_path, monkeypatch):
    mod = _load_module()
    doc = tmp_path / "CURRENT-STATE.md"
    doc.write_text(FIXTURE_WITH_MARKERS, encoding="utf-8")
    monkeypatch.setattr(mod, "CURRENT_STATE", doc)
    return mod


def test_render_table_basic_shape(st):
    table = st.render_table([("Label", "Value", "Note")])
    assert table.splitlines()[0] == "| | Value | Notes |"
    assert "| Label | Value | Note |" in table


def test_apply_replaces_only_content_between_markers(st):
    rows = [("Backend branch / commit", "`main`, `abc123`", "measured")]
    st.apply(rows)
    text = st.CURRENT_STATE.read_text(encoding="utf-8")
    assert "OLD CONTENT THAT SHOULD BE REPLACED" not in text
    assert "abc123" in text
    # Untouched surroundings survive verbatim.
    assert "Some narrative prose above the table, untouched by --apply." in text
    assert "hand-maintained row" in text
    assert "More prose below, also untouched." in text
    # Markers themselves survive so a second --apply still finds them.
    assert st.MARKER_START in text
    assert st.MARKER_END in text


def test_apply_is_idempotent(st):
    rows = [("Backend branch / commit", "`main`, `abc123`", "measured")]
    st.apply(rows)
    once = st.CURRENT_STATE.read_text(encoding="utf-8")
    st.apply(rows)
    twice = st.CURRENT_STATE.read_text(encoding="utf-8")
    assert once == twice


def test_apply_raises_if_markers_missing(tmp_path, monkeypatch):
    mod = _load_module()
    doc = tmp_path / "CURRENT-STATE.md"
    doc.write_text("# no markers here\n", encoding="utf-8")
    monkeypatch.setattr(mod, "CURRENT_STATE", doc)
    with pytest.raises(SystemExit):
        mod.apply([("x", "y", "z")])


def test_git_branch_not_hardcoded_to_master(st):
    # Regression guard: the table used to hardcode the literal string "master" regardless
    # of the real branch (a latent bug -- this repo's default branch is "main").
    branch = st.git_branch()
    assert branch  # actual branch name of whatever repo/worktree runs the test
