r"""Generate the CURRENT-STATE.md "Build state" table from direct, measured commands.

Replaces manual re-derivation of this table by an agent every session -- the previous manual
process is exactly what nearly collided two sessions on CURRENT-STATE.md (see
docs/reviews/fable-workflow-2026-07-27.md, work order W4).

Usage:
    python tools/state.py                  # print the table to stdout (fast: no test suites)
    python tools/state.py --tests          # also run backend + frontend suites (slow: ~4 min)
    python tools/state.py --apply          # write the table into docs/CURRENT-STATE.md in place
    python tools/state.py --apply --tests  # both

--apply replaces only the content between the `<!-- BUILD-STATE:START -->` /
`<!-- BUILD-STATE:END -->` markers in docs/CURRENT-STATE.md. Everything else in that file --
narrative prose, the "Agent infrastructure" / "Frontend location" rows above the markers, ADR
summaries -- is untouched. Those rows aren't included here because they aren't measurable by a
single command the way commit/contract/counts are; they stay hand-maintained, per CLAUDE.md's
"narrative sections of CURRENT-STATE are edited only by the session whose work changed them."

Backend tests run under whichever interpreter invoked this script (`sys.executable`) --
not a hardcoded path. On the founder's Windows machine that is the project's conda env
(activate it before running this); on a cloud/Linux session it is whatever `python3`
resolved on PATH per docs/environment.md. A hardcoded
`C:\Users\...\miniconda3\envs\fantasyfootball\python.exe` here previously hard-crashed
every non-Windows session that passed --tests (found during the cloud-rebuild session,
2026-07-29) -- it is exactly the kind of env-specific literal docs/environment.md warns
sessions to check for before assuming a path in this repo is portable.
"""
import argparse
import re
import shutil
import subprocess
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
BACKEND_PYTHON = sys.executable
CURRENT_STATE = REPO_ROOT / "docs" / "CURRENT-STATE.md"
MARKER_START = "<!-- BUILD-STATE:START (generated by `python tools/state.py --apply` -- do not hand-edit between these markers) -->"
MARKER_END = "<!-- BUILD-STATE:END -->"


def _rel(path: Path) -> str:
    """Best-effort path-for-humans. Falls back to the absolute path when the given
    path isn't under REPO_ROOT (e.g. a test pointed the module at a scratch tmp_path)."""
    try:
        return str(path.relative_to(REPO_ROOT))
    except ValueError:
        return str(path)


def run(cmd, cwd=REPO_ROOT, timeout=600):
    # Resolve argv[0] through PATH before handing it to CreateProcess. On Windows
    # `npx` is `npx.cmd` and a bare "npx" raises FileNotFoundError, which is how
    # --tests failed the first time this ran on the project's own machine.
    # shutil.which applies PATHEXT, so it finds .cmd/.exe/.bat without hardcoding
    # an extension or resorting to shell=True with a list argv.
    if not isinstance(cmd, str):
        cmd = list(cmd)
        resolved = shutil.which(cmd[0])
        if resolved:
            cmd[0] = resolved
    result = subprocess.run(
        cmd, cwd=cwd, capture_output=True, text=True, shell=isinstance(cmd, str), timeout=timeout
    )
    return result.returncode, result.stdout, result.stderr


def git_branch():
    code, out, err = run(["git", "rev-parse", "--abbrev-ref", "HEAD"])
    if code != 0:
        return f"ERROR: {err.strip()}"
    return out.strip()


def git_head():
    code, out, err = run(["git", "rev-parse", "HEAD"])
    if code != 0:
        return f"ERROR: {err.strip()}"
    return out.strip()


def contract_version():
    path = REPO_ROOT / "src" / "export_contract.py"
    if not path.exists():
        return "ERROR: src/export_contract.py not found"
    text = path.read_text(encoding="utf-8")
    match = re.search(r'CONTRACT_VERSION\s*=\s*["\']([^"\']+)["\']', text)
    return match.group(1) if match else "ERROR: CONTRACT_VERSION not found"


def module_count():
    return len(list((REPO_ROOT / "src").glob("*.py")))


def export_artifact_count():
    export_dir = REPO_ROOT / "data" / "export"
    if not export_dir.exists():
        return "ERROR: data/export not found"
    return len(list(export_dir.glob("*.json")))


def config_dir_count():
    export_dir = REPO_ROOT / "data" / "export"
    if not export_dir.exists():
        return 0
    return len([p for p in export_dir.iterdir() if p.is_dir()])


def backend_test_summary():
    code, out, err = run([BACKEND_PYTHON, "-m", "pytest", "-q"], timeout=900)
    lines = [ln for ln in (out + err).splitlines() if ln.strip()]
    # pytest's summary line is the last non-empty line, e.g. "512 passed in 200.97s"
    return lines[-1] if lines else f"ERROR (exit {code})"


def frontend_test_summary():
    frontend_dir = REPO_ROOT / "frontend"
    if not frontend_dir.exists():
        return "ERROR: frontend/ not found"
    code, out, err = run(["npx", "vitest", "run"], cwd=frontend_dir, timeout=600)
    text = out + err
    files_match = re.search(r"Test Files\s+(.+)", text)
    tests_match = re.search(r"Tests\s+(.+)", text)
    if files_match and tests_match:
        return f"{tests_match.group(1).strip()} ({files_match.group(1).strip()})"
    return f"ERROR (exit {code}) — could not parse summary"


def build_rows(run_tests: bool):
    rows = [
        ("Backend branch / commit", f"`{git_branch()}`, `{git_head()}`", "`git rev-parse --abbrev-ref HEAD` / `HEAD`"),
        ("Data contract", f"`{contract_version()}`", "`CONTRACT_VERSION` in `src/export_contract.py`"),
        ("Python modules", f"{module_count()}", "`src/*.py`, counted"),
        ("Export artifacts", f"{export_artifact_count()}", "top-level files in `data/export/`"),
        ("Config matrix", f"{config_dir_count()}", "dirs under `data/export/`"),
    ]
    if run_tests:
        print("Running backend suite (this is slow)...", file=sys.stderr)
        rows.append(("Backend tests", backend_test_summary(), "`pytest -q`, single run"))
        print("Running frontend suite (this is slow)...", file=sys.stderr)
        rows.append(("Frontend tests", frontend_test_summary(), "`npx vitest run`, single run"))
    else:
        rows.append(("Backend tests", "(skipped — pass --tests to run the suite)", ""))
        rows.append(("Frontend tests", "(skipped — pass --tests to run the suite)", ""))
    return rows


def render_table(rows) -> str:
    lines = ["| | Value | Notes |", "|---|---|---|"]
    for label, value, note in rows:
        lines.append(f"| {label} | {value} | {note} |")
    return "\n".join(lines)


def apply(rows):
    if not CURRENT_STATE.exists():
        raise SystemExit(f"state.py --apply: {CURRENT_STATE} not found")
    text = CURRENT_STATE.read_text(encoding="utf-8")
    if MARKER_START not in text or MARKER_END not in text:
        raise SystemExit(
            "state.py --apply: markers not found in docs/CURRENT-STATE.md -- "
            f"expected both:\n  {MARKER_START}\n  {MARKER_END}"
        )
    before, rest = text.split(MARKER_START, 1)
    _, after = rest.split(MARKER_END, 1)
    new_text = before + MARKER_START + "\n\n" + render_table(rows) + "\n\n" + MARKER_END + after
    CURRENT_STATE.write_text(new_text, encoding="utf-8")
    print(f"state.py --apply: wrote build-state table into {_rel(CURRENT_STATE)}")


def main():
    # Some Windows terminals default stdout to cp1252, which cannot encode the em dashes
    # used in this file's output. Reconfigure rather than let a print() crash the command.
    try:
        sys.stdout.reconfigure(encoding="utf-8", errors="replace")
    except Exception:
        pass
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument(
        "--tests", action="store_true", help="also run backend + frontend suites (slow, ~4 min)"
    )
    parser.add_argument(
        "--apply", action="store_true", help="write the table into docs/CURRENT-STATE.md between its markers"
    )
    args = parser.parse_args()

    rows = build_rows(args.tests)

    if args.apply:
        apply(rows)
    else:
        print(render_table(rows))


if __name__ == "__main__":
    main()
